image:
  - Visual Studio 2019
  - Ubuntu
environment:
  matrix:
    - RUST_TOOL_CHAIN: stable
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: '**\*.nupkg'
    name: nupkg
  - path: '**\*.snupkg'
    name: snupkg
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: nNWiXk+ZiOOh5sHV/C9Z9pqZ8GFpaQFqAR/P0/t09h81Ppx3xed6VsWd4w7FMn2R
  on:
    branch: master
    #appveyor_repo_tag: true
matrix:
  fast_finish: true
for:
  - matrix:
      only:
        - image: Ubuntu
    install:
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOL_CHAIN}
      - source $HOME/.cargo/env
      - rustup component add rustfmt
    build_script:
      - cargo build --release --manifest-path xdelta3-rs/Cargo.toml
      - dotnet build -c Release dotnet/redist/linux-x64
    test_script:
      - dotnet test -c Release dotnet
  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      - scoop install rustup
      - refreshenv
      #- SET PATH=%USERPROFILE%\scoop\apps\rustup\current\.cargo\bin;%PATH%
      - rustup default %RUST_TOOL_CHAIN%
      - rustup component add rustfmt
      #- SET PATH=%USERPROFILE%\.cargo\bin;C:\MinGW\bin;%PATH%
      - rustc -V
      - cargo -V
    build_script:
      - dotnet test -c Release dotnet
      - cargo build --release --manifest-path xdelta3-rs/Cargo.toml
      - dotnet build -c Release dotnet/redist/win-x64
